//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkLevel.ShipDamageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipStatus", Namespace="http://schemas.datacontract.org/2004/07/HonorInterfaces")]
    [System.SerializableAttribute()]
    public partial class ShipStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ShipGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NetworkLevel.ShipDamageService.ShipSubsystemStatus[] SubsystemStatusesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ShipGuid {
            get {
                return this.ShipGuidField;
            }
            set {
                if ((this.ShipGuidField.Equals(value) != true)) {
                    this.ShipGuidField = value;
                    this.RaisePropertyChanged("ShipGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetworkLevel.ShipDamageService.ShipSubsystemStatus[] SubsystemStatuses {
            get {
                return this.SubsystemStatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubsystemStatusesField, value) != true)) {
                    this.SubsystemStatusesField = value;
                    this.RaisePropertyChanged("SubsystemStatuses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipSubsystemStatus", Namespace="http://schemas.datacontract.org/2004/07/HonorInterfaces")]
    [System.SerializableAttribute()]
    public partial class ShipSubsystemStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NetworkLevel.ShipDamageService.RanmaRepairSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubSystemNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetworkLevel.ShipDamageService.RanmaRepairSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubSystemNum {
            get {
                return this.SubSystemNumField;
            }
            set {
                if ((this.SubSystemNumField.Equals(value) != true)) {
                    this.SubSystemNumField = value;
                    this.RaisePropertyChanged("SubSystemNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RanmaRepairSeverity", Namespace="http://schemas.datacontract.org/2004/07/HonorInterfaces")]
    public enum RanmaRepairSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Easy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hard = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShipDamageService.IServerDamageContract", CallbackContract=typeof(NetworkLevel.ShipDamageService.IServerDamageContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServerDamageContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerDamageContract/ServerConnect", ReplyAction="http://tempuri.org/IServerDamageContract/ServerConnectResponse")]
        void ServerConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerDamageContract/SetAllSubsystemsStatuses", ReplyAction="http://tempuri.org/IServerDamageContract/SetAllSubsystemsStatusesResponse")]
        void SetAllSubsystemsStatuses(NetworkLevel.ShipDamageService.ShipStatus[] shipStatuses);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerDamageContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerDamageContract/DamageShip", ReplyAction="http://tempuri.org/IServerDamageContract/DamageShipResponse")]
        bool DamageShip(System.Guid shipGuid, NetworkLevel.ShipDamageService.ShipSubsystemStatus subsystemStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerDamageContract/DestroyShip", ReplyAction="http://tempuri.org/IServerDamageContract/DestroyShipResponse")]
        bool DestroyShip(System.Guid shipGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerDamageContractChannel : NetworkLevel.ShipDamageService.IServerDamageContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerDamageContractClient : System.ServiceModel.DuplexClientBase<NetworkLevel.ShipDamageService.IServerDamageContract>, NetworkLevel.ShipDamageService.IServerDamageContract {
        
        public ServerDamageContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServerDamageContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServerDamageContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServerDamageContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServerDamageContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ServerConnect() {
            base.Channel.ServerConnect();
        }
        
        public void SetAllSubsystemsStatuses(NetworkLevel.ShipDamageService.ShipStatus[] shipStatuses) {
            base.Channel.SetAllSubsystemsStatuses(shipStatuses);
        }
    }
}
