update=11/11/2011 01:11:50
version=1
last_client=eeschema
[general]
version=1
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
PadDrlX=0
PadDimH=170
PadDimV=890
BoardThickness=630
SgPcb45=1
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=50
LastNetListRead=tirno.net
[pcbnew/libraries]
LibDir=
LibName1=D:\\SVN\\Token\\TokenSmartCard\\Hardware\\trunk\\KiCadLibs\\Common_kl
LibName2=D:\\SVN\\Token\\TokenSmartCard\\Hardware\\trunk\\KiCadLibs\\Connectors_kl
LibName3=D:\\SVN\\Token\\TokenSmartCard\\Hardware\\trunk\\KiCadLibs\\display_kl
LibName4=D:\\SVN\\Token\\TokenSmartCard\\Hardware\\trunk\\KiCadLibs\\pcb_details
LibName5=D:\\SVN\\Token\\TokenSmartCard\\Hardware\\trunk\\KiCadLibs\\Tittar_kl
[eeschema]
version=1
LibDir=
NetFmt=1
HPGLSpd=20
HPGLDm=15
HPGLNum=1
offX_A4=0
offY_A4=0
offX_A3=0
offY_A3=0
offX_A2=0
offY_A2=0
offX_A1=0
offY_A1=0
offX_A0=0
offY_A0=0
offX_A=0
offY_A=0
offX_B=0
offY_B=0
offX_C=0
offY_C=0
offX_D=0
offY_D=0
offX_E=0
offY_E=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Atmel_kl
LibName2=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Connectors_kl
LibName3=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/display_kl
LibName4=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/pcb_details
LibName5=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/power
LibName6=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Power_kl
LibName7=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/RF ICs
LibName8=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Tittar_kl
LibName9=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Transistors_kl
LibName10=D:/SVN/Token/TokenSmartCard/Hardware/trunk/KiCadLibs/Interface_kl
