#ifndef _NAMESPACE_PROTECT_
	#error "Use ArmletShell.h"
#endif

#define BUTTON_HOLD_OFFSET 100

#define BUTTON_HOLD_A	BUTTON_HOLD_OFFSET  + BUTTON_A
#define BUTTON_HOLD_B	BUTTON_HOLD_OFFSET	+ BUTTON_B
#define BUTTON_HOLD_C	BUTTON_HOLD_OFFSET	+ BUTTON_C
						
#define BUTTON_HOLD_X	BUTTON_HOLD_OFFSET	+ BUTTON_X
#define BUTTON_HOLD_Y	BUTTON_HOLD_OFFSET	+ BUTTON_Y
#define BUTTON_HOLD_Z	BUTTON_HOLD_OFFSET  + BUTTON_Z
						
#define BUTTON_HOLD_L	BUTTON_HOLD_OFFSET	+ BUTTON_L
#define BUTTON_HOLD_E	BUTTON_HOLD_OFFSET	+ BUTTON_E
#define BUTTON_HOLD_R	BUTTON_HOLD_OFFSET	+ BUTTON_R